include /etc/nginx/mime.types;

daemon off;

server {
    listen 80;

    location ~* \.(js)$ {
        root /etc/app/dist;
    }

    location ~* (.*/country)/(.+\.svg)$ {
        root /etc/app/static/;
        autoindex on;
    }

    location / {
        proxy_pass http://localhost:8050;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}