version: 0.2
phases:
  install:
    runtime_versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging into ecr
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URL=581758326652.dkr.ecr.us-east-1.amazonaws.com/sigmyze-containers
      - echo Logged into ECR!
  build:
    commands:
      #build the docker images
      - echo Building the docker images
      - docker build -t $REPOSITORY_URL/dotnet -f web/SigmyzeServer/Dockerfile .
      - echo Built the DOTNET docker layer
      - docker build -t $REPOSITORY_URL/application -f web/ui-next/Dockerfile .
      - echo Built the NextJS layer
      - docker build -t $REPOSITORY_URL/nginx -f web/nginx/Dockerfile .
      - echo build the nginx layer
  post_build:
    commands:
      - echo Pushing the docker images
      - docker push $REPOSITORY_URL/dotnet
      - echo Pushed the DOTNET docker layer
      - docker push $REPOSITORY_URL/application
      - echo Pushed the NextJS layer
      - docker push $REPOSITORY_url/nginx
      - echo Pushed the nginx layer