version: '2.2'

services:
    dotnet:
        build: 
            context: .
            dockerfile: ./Server.Dockerfile
        ports:
            - "8013:80"
        restart: always
    nginx:
        build: 
            context: .
            dockerfile: ./NginX.Dockerfile
        ports:
            - "80:80"
        restart: always