version: '1'

services:
    dotnet:
        build: 
            context: .
            dockerfile: ./Server.Dockerfile
        ports:
            - "80:80"
        expose:
            - 80
    nginx:
        build: 
            context: .
            dockerfile: ./NginX.Dockerfile
        ports:
            - "8080:80"