version: "3"

services:
  nginx:
    build:
      context: web/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - sigmyze-server
  sigmyze-server:
    build:
      context: web/SigmyzeServer
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2015:80"
  quanta-server:
    build:
      context: web/QuantaEngine
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5025:80"
  application:
    build: 
      context: web/ui-next
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - nginx