server {
    listen 80;
    listen [::]:80;

    server_name  sigmyze.com www.sigmyze.com;

    return 301 https://sigmyze.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name  sigmyze.com www.sigmyze.com;

    ssl_certificate     /etc/letsencrypt/live/sigmyze.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sigmyze./privkey.pem;

    location /api {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://dotnet:80;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }

    location ~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}