/**
 * this is the datastructure that defines how all filesystems will be stored in sigmyze
 */
interface ISigmyzeFilesystem {
    /**
     * this is the name for the filesystem.
     * currently has no real uses other than tagging
     */
    name: string,

    /**
     * these are the folders in the filesystem
     */
    folders: ISigmyzeFolder[],

    /**
     * these are the files in the root folder of the filesystem
     */
    files: ISigmyzeFile[]
}

/**
 * this is the datastructure definition of the SigmyzeFolder
 */
interface ISigmyzeFolder {
    /**
     * this is the name of the folder
     */
    folderName: string,

    /**
     * this is the id of the folder, used to track and make changes within the filesystem
     * best to be generated by using uuid v4() or something similar
     */
    folderId: string,

    /**
     * theese are all the child folders in this folder
     */
    folders: ISigmyzeFolder[],

    /**
     * theese are all the child files in this folder
     */
    files: ISigmyzeFile[],

    /**
     * whether or not this folder should be opened on the file-tree mount
     */
    openMount?: boolean
}

/**
 * this is the datastructure definition for the sigmyze file
 */
interface ISigmyzeFile {
    /**
     * this is the display name of the file
     */
    fileName: string,

    /**
     * this is the type of the file, currently supported types are
     *  - quanta::chart -> this is a quanta-chart in the lunar editor
     *  - quanta::note -> this is a quanta-note in the lunar editor
     */
    fileType: string,

    /**
     * NOTE: This is an unimplemented feature
     * custom icon to be displayed instead of normal type based icon
     */
    fileIcon?: React.ReactElement,

    /**
     * this is the id of the file, used to refer to the file and make changes
     */
    fileId: string
}

export type {
    ISigmyzeFilesystem,
    ISigmyzeFolder,
    ISigmyzeFile
}