/**
 * this is the datastructure that defines how all filesystems will be stored in sigmyze
 */
interface ISigmyzeFilesystem {
    /**
     * this is the name for the filesystem.
     * currently has no real uses other than tagging
     */
    name: string,

    /**
     * these are the folders in the filesystem
     */
    folders: ISigmyzeFolder[],

    /**
     * these are the files in the root folder of the filesystem
     */
    files: ISigmyzeFile[]
}

/**
 * this is the datastructure definition of the SigmyzeFolder
 */
interface ISigmyzeFolder {
    /**
     * this is the name of the folder
     */
    folderName: string,

    /**
     * this is the id of the folder, used to track and make changes within the filesystem
     * best to be generated by using uuid v4() or something similar
     */
    folderId: string,

    /**
     * theese are all the child folders in this folder
     */
    folders: ISigmyzeFolder[],

    /**
     * theese are all the child files in this folder
     */
    files: ISigmyzeFile[],

    /**
     * whether or not this folder should be opened on the file-tree mount
     */
    openMount?: boolean,

    /**
     * this is the persisted open state of the folder, which is saved to disk / memory
     */
    openState?: boolean
}

/**
 * this is the unique datastructure meant for the optional children of a sigmyze file
 */
interface ISigmyzeFileChild {
    /**
     * This is the icon that will be displayed alongside the child's text
     */
    icon: React.ReactElement,

    /**
     * This is the text that the child will display
     */
    text: string
}

/**
 * this is the datastructure definition for the sigmyze file
 */
interface ISigmyzeFile {
    /**
     * this is the display name of the file
     */
    fileName: string,

    /**
     * this is the type of the file, currently supported types are
     *  - quanta::chart -> this is a quanta-chart in the lunar editor
     *  - quanta::note -> this is a quanta-note in the lunar editor
     */
    fileType: string,

    /**
     * NOTE: This is an unimplemented feature
     * custom icon to be displayed instead of normal type based icon
     */
    fileIcon?: React.ReactElement,

    /**
     * this is the id of the file, used to refer to the file and make changes
     */
    fileId: string,

    /**
     * this is the children that are rendered with the file (not stored outside of sigmyze filesystem)
     * they are not to be displayed unless the file is focused
     */
    children?: ISigmyzeFileChild[]
}

/**
 * this is the datastructure definition for the simple filesystem
 * all filesystems that will be stored on a server, should use this format as it removes any project based abstractions
 */
interface ISimpleFilesystem {
    /**
     * theese are the folders within the simple filesystem
     */
    folders: ISimpleFolder[],

    /**
     * theese are the fileId's of the files stored within the root folder of the simple filesystem
     */
    files: string[]
}

/**
 * this is the datastructure definition for the folder within the simple filesystem
 */
interface ISimpleFolder {
    /**
     * this is the name for the simplefolder
     */
    folderName: string,

    /**
     * this is the ID that was generated within the sigmyze filesystem for the simple folder
     */
    folderId: string,

    /**
     * theese are all the subfolders within the simplefolder
     */
    folders: ISimpleFolder[],

    /**
     * theese are all the fileID's within the simple folder
     */
    files: string[]
}

export type {
    ISigmyzeFilesystem,
    ISigmyzeFolder,
    ISigmyzeFile,
    ISimpleFilesystem,
    ISimpleFolder,
    ISigmyzeFileChild
}